# Expose Health and Prometheus endpoints natively for Grafana scraping
management.endpoints.web.exposure.include=health,prometheus

# Provide deep diagnostics of database/disk disk space
management.endpoint.health.show-details=always

# Explicitly tag metrics so AWS / Grafana can dynamically filter by application
management.metrics.tags.application=BarcodeScannerService
